### ISSUE TITLE
Migration to GitHub is not complete

### ISSUE THREAD

**Issue by Neustradamus** [libexpat/libexpat#540] opened 2022-01-09 03:09 UTC
Dear @libexpat team,

In first, I wish you a Happy New Year.

It will be nice to remove old parts like:
- https://sourceforge.net/p/expat/wiki/Home/
- https://sourceforge.net/p/expat/_list/tickets
- https://sourceforge.net/p/expat/bugs/
- https://sourceforge.net/p/expat/patches/
- https://sourceforge.net/p/expat/news/
- https://sourceforge.net/p/expat/code/
- https://sourceforge.net/p/expat/code_git/

Can you add a "move" box like https://sourceforge.net/projects/handbrake for example.
- https://sourceforge.net/p/expat/

To disable/delete tabs, go here: https://sourceforge.net/projects/expat/
To add a new tab, go here: https://sourceforge.net/projects/expat/
To change informations, go here: https://sourceforge.net/p/expat/admin/overview
To export, go here: https://sourceforge.net/p/expat/admin/export

The new place can be added in:
- "Moved Project to", here: https://sourceforge.net/p/expat/admin/overview
- "Preferred Support Page (for users of your project)", here: https://sourceforge.net/p/expat/admin/overview
- A new tab, go here: https://sourceforge.net/projects/expat/

Thanks in advance.

**Comment by hartwork** [comment] 2022-01-09 12:35
Hi @Neustradamus ,

the SourceForge project was pointing to GitHub at multiple places already — at the entry page, the getting help page, and also inside the SF git repo — but I have added the "move box" now for extra attention. Other than that ticket this seems like a duplicate of ticket #1. Which transition points deserves more attention in particular?

Thanks and best, Sebastian

**Comment by Neustradamus** [comment] 2022-01-09 13:09
@hartwork: Thanks for your reply!

I have not seen before the ticket number 1, it has been created a very long time ago, it will be nice to finish the migration.

You can add a link to this place in tabs, it is free ;)
Can you remove/disable old parts in Sourceforge?

**Comment by hartwork** [comment] 2022-01-09 13:17
> You can add a link to this place in tabs, it is free ;)

I have added a new tab named "GitHub" pointing to https://github.com/libexpat/libexpat/ now. Do we need anything more?

> Can you remove/disable old parts in Sourceforge?

Which parts in particular?

**Comment by Neustradamus** [comment] 2022-01-09 13:26
Thanks, why not harmonize, I see:
- https://github.com/libexpat/libexpat/issues ("Preferred Support Page (for users of your project)")
- https://github.com/libexpat/libexpat (tab)
- https://libexpat.github.io/ ("Moved Project to" + website)

I think that the best is https://github.com/libexpat.

> It will be nice to remove old parts like:
> 
> * https://sourceforge.net/p/expat/wiki/Home/
> * https://sourceforge.net/p/expat/_list/tickets
> * https://sourceforge.net/p/expat/bugs/
> * https://sourceforge.net/p/expat/patches/
> * https://sourceforge.net/p/expat/news/
> * https://sourceforge.net/p/expat/code/
> * https://sourceforge.net/p/expat/code_git/
>

**Comment by hartwork** [comment] 2022-01-09 13:36
> Thanks, why not harmonize, I see:
> 
>     * https://github.com/libexpat/libexpat/issues ("Preferred Support Page (for users of your project)")

With two or more external links, SourceForge will now put them in a dropdown "External Link", with rather little visibility. I'm not sure I see the point of adding more links to that place.

>     * https://github.com/libexpat/libexpat (tab)

That's done already, as mentioned above.


>     * https://libexpat.github.io/ ("Moved Project to" + website)

Also already done, as mentioned above.


> > It will be nice to remove old parts like:
> > 
> > * https://sourceforge.net/p/expat/wiki/Home/

Has one question with answer on the front page, no clear gain from removal.

> > * https://sourceforge.net/p/expat/_list/tickets
> > * https://sourceforge.net/p/expat/bugs/
> > * https://sourceforge.net/p/expat/patches/

Those have archival value, should be kept.

> > * https://sourceforge.net/p/expat/news/

I have added an entry [Project moved to GitHub](https://sourceforge.net/p/expat/news/). With that added, it can be kept as an archive, I consider that point done.

> > * https://sourceforge.net/p/expat/code/

No idea how to disable that page. (Does seem to do big damage either.)

> > * https://sourceforge.net/p/expat/code_git/

Points to GitHub, good enough in my view.

@Neustradamus what is left to do?

**Comment by hartwork** [comment] 2022-01-09 13:51
> With two or more external links, SourceForge will now put them in a dropdown "External Link", with rather little visibility. I'm not sure I see the point of adding more links to that place.

@Neustradamus PS: "Fixed" by increasing group count to >2, so it's separate "buttons" again now. Also added on more "Documentation" pointing to https://libexpat.github.io/ . Maybe that's enough then, all else can be reached from those.

**Comment by Neustradamus** [comment] 2022-01-09 14:31
At origine, I said to have only one link (box, website, support page, tab) to https://github.com/libexpat instead of https://libexpat.github.io/ or https://github.com/libexpat/libexpat/issues or https://github.com/libexpat/libexpat.

Website and support links can be https://github.com/libexpat, all are in tabs now.

1/ "This is James Clark's Expat XML parser library in C. It is a stream oriented parser that requires setting handlers to deal with the structure that the parser discovers in the document." from https://sourceforge.net/p/expat/wiki/Home/ can be added in project description.

2/ You can export and import in GitHub: https://sourceforge.net/p/expat/admin/export

3/ In tab, lock and gear, the menu...

4/ No interrest... GitHub links are in tabs.

5/ Some links are in "...", better to remove (wiki, bugs, patches, code, code_git), more clear.

**Comment by hartwork** [comment] 2022-01-09 14:39
I'll consider this done then, with the exception of the known open items at https://github.com/libexpat/libexpat/issues/1#issue-203837554 . Closing.

**Closed by hartwork** 2022-01-09 14:39 UTC

**Comment by Neustradamus** [comment] 2022-01-10 03:21
@hartwork: Can you change the place of News?
I do not see this tab, it is in "...".
Screenshot: https://i.ibb.co/7gY12nh/sourceforge-expat-project.png

You can change all https://github.com/libexpat/libexpat links to https://github.com/libexpat.
Better to have the GitHub organization ^^

Thanks in advance.

**Comment by hartwork** [comment] 2022-01-10 16:15
> @hartwork: Can you change the place of News? I do not see this tab, it is in "...". Screenshot: https://i.ibb.co/7gY12nh/sourceforge-expat-project.png

Done.
