### ISSUE TITLE
test_big_tokens_take_linear_time failing on Solaris

### ISSUE THREAD

**Issue by kulikjak** [libexpat/libexpat#830] opened 2024-02-22 09:33 UTC
Hi, I updated libexpat to 2.6.0 on Solaris and found out that `test_big_tokens_take_linear_time` is failing with the following error:
```
ERROR: check failed: taken > 0
Expat version: expat_2.6.0
FAIL [chunksize=0 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15 text="<a>aaaaaa</a>" at ./expat-2.6.0/tests/basic_tests.c:5293)
```

The reason seems to be that `clock()` on Solaris doesn't have a good enough resolution. While `CLOCKS_PER_SEC` is high enough (to pass the already existing check), it seems to tik only 1000 times a second (with big increments).

Internally I added the following patch:
```diff
--- expat-2.6.0/tests/basic_tests.c
+++ expat-2.6.0/tests/basic_tests.c
@@ -5243,6 +5243,11 @@ START_TEST(test_big_tokens_take_linear_t
     return;
   }
 #endif
+#if defined(__sun) && defined(__SVR4)
+  // On Solaris, clock() doesn't have a good enough resolution (even
+  // though CLOCKS_PER_SEC is high enough to pass the test above).
+  return;
+#endif
 
   clock_t baseline = 0;
   for (int i = 0; i < num_cases; ++i) {
```
I can create a PR if you think this is acceptable.

**Comment by hartwork** [comment] 2024-02-22 19:42
Hi @kulikjak,

sorry for the inconvenience. I believe this is a duplicate of #825 and #827 and that it's already fixed on `master` by #817. There are other Expat topics in flight at the moment that will need more clarity before making a follow-up release, but report here being the third case on the topic clearly shows that a soon new release with a fix is needed.

Regarding Solaris, are you aware of an economic way of adding Solaris coverage to GitHub Actions CI? Something like that would help getting Solaris into the zone of officially supported in 2024. Before that I'll need to to at least think twice before accepting patches that will be known to not covered by CI. Which distribution of Solaris is this about btw — OpenCSW, OpenIndiana, ORACLE Solaris, …?

Best, Sebastian

**Comment by hartwork** [comment] 2024-02-26 23:01
Closing as fixed on `master`…

> Regarding Solaris, are you aware of an economic way of adding Solaris coverage to GitHub Actions CI? Something like that would help getting Solaris into the zone of officially supported in 2024. Before that I'll need to to at least think twice before accepting patches that will be known to not covered by CI. Which distribution of Solaris is this about btw — OpenCSW, OpenIndiana, ORACLE Solaris, …?

Would still be curious about your thought on that^^ aspect. Thanks!

**Closed by hartwork** 2024-02-26 23:01 UTC
Labels: question

**Comment by kulikjak** [comment] 2026-01-06 14:16
Hi @hartwork, I am very sorry - I must have missed the notification about this comment and only now realized that it exists and that I should answer it...

> > Regarding Solaris, are you aware of an economic way of adding Solaris coverage to GitHub Actions CI? Something like that would help getting Solaris into the zone of officially supported in 2024. Before that I'll need to to at least think twice before accepting patches that will be known to not covered by CI. Which distribution of Solaris is this about btw — OpenCSW, OpenIndiana, ORACLE Solaris, …?
> 
> Would still be curious about your thought on that^^ aspect. Thanks!

I encountered this on Oracle Solaris.

I personally haven't play with it much, but there is a way of running VM with Solaris on GitHub actions using [this](https://github.com/vmactions/solaris-vm). And there are several projects using it like e.g. rust-lang libc: https://github.com/rust-lang/libc/commit/741264c03358a0625ae11f46024e4ea085fb88df

I think that should work for libexpat as well?

Sorry once more and happy new year!

**Comment by kulikjak** [comment] 2026-01-13 16:37
Or, if you want to keep the package installation part to be sure those are always there, something like `|| true` needs to be added, because `pkg` exits with `3` or `4` when it installs only some or none of the listed packages.

I can open a PR with preferred change if you want.
