### ISSUE TITLE
Inconsistent CMake imported target between msvc and others compilers

### ISSUE THREAD

**Issue by SpaceIm** [libexpat/libexpat#407] opened 2020-07-09 09:26 UTC
`expat` creates `expat-config.cmake` and `expat.cmake` for CMake imported targets.

Inside `expat.cmake`, target name is inconsistent between Visual Studio and others compilers, which is not very "portable friendly":
Visual Studio: `expat::libexpat`
others: `expat::expat`

Moreover, CMake findEXPAT defines `EXPAT::EXPAT` target: https://cmake.org/cmake/help/v3.18/module/FindEXPAT.html

It's probably too late to make things consistent between findEXPAT and config/target generated files, but at least it would be nice to use `expat::expat` even for Visual Studio.

**Comment by hartwork** [comment] 2020-07-09 17:23
I think these lines may answer 95% of your questions:
https://github.com/libexpat/libexpat/blob/253686453276a045510d29f4eeef778169929b3a/expat/CMakeLists.txt#L280-L293

Did you see those? With those in mind, what is left that I can help you with?

**Comment by SpaceIm** [comment] 2020-07-09 17:58
I saw this branching. It solves filename conflicts, but there is no reason to change CMake target name, only dll file name. It puts pressure to consumers who have to figure out which CMake target to use based on compiler.

**Comment by hartwork** [comment] 2020-07-09 18:46
Maybe let's cool this down a bit, I'm happy to improve what can be improved. Let's find out, happy to learn something new about CMake myself.
Symbol `EXPAT_TARGET` is currently exported for that very reason: To not have reverse dependencies need to guess the target name, duplicating the branching. If we revert the target name back to plain "expat" we'll need ways to have the resulting filenames be what they are now, by some other means. What other options do we have to affect filenames that you're aware of?

**Comment by SpaceIm** [comment] 2020-07-10 07:35
Sorry, didn't mean to be rude.
CMake targets have `PREFIX`, `OUTPUT_NAME` and `SUFFIX` properties which can be modifed. I think that setting either `PREFIX` to `lib` or `OUTPUT_NAME` to `libexpat` if MSVC should be fine.

**Comment by hartwork** [comment] 2020-07-10 17:38
I'm starting a test balloon on this at pull request #408, please be invited for review. The effect I see locally is as desired but let's see if CI finds a problem that I overlooked.

**Comment by Neumann-A** [comment] 2020-08-19 20:06
@hartwork:

I would ask you to keep the archive name on windows via [ARCHIVE_OUTPUT_NAME](https://cmake.org/cmake/help/latest/prop_tgt/ARCHIVE_OUTPUT_NAME.html) always as expat (static/import lib) while you can control the dll name via [LIBRARY_OUTPUT_NAME](https://cmake.org/cmake/help/latest/prop_tgt/LIBRARY_OUTPUT_NAME.html#prop_tgt:LIBRARY_OUTPUT_NAME). I would suggest to use a versioned dll name to avoid conflicts. 
The problem is simply a lot of autotools based ports which do not used pkg-config for expat expect the name to be simply expat.

**Comment by hartwork** [comment] 2020-08-20 18:41
@Neumann-A issues #407 was about issues with dynamic changes in target name, not filename. That has been address by pull request #408 and hence issue #407 should have been closed as fixed (but simply was forgotten to and left open). Hence I'm closing it as fixed now.
I'm happy discuss further changes to CMake in a new dedicated ticket. Please provide more context in that new ticket.

**Closed** 2020-08-20 18:42 UTC
Labels: compilation, enhancement
