### ISSUE TITLE
Facing build failures in doc folder in expat from version 2.6.2

### ISSUE THREAD

**Issue by anjuvmenon** [libexpat/libexpat#909] opened 2024-10-10 12:39 UTC
Hi Team,
I am trying to upgrade expat library in our project.The version used is 2.6.3.We are extracting the expat tarball and bundling it in our source code.The same process we were following for the previous versions as well.In the latest version 2.6.3 we are getting this following build error when we try to compile our source code with the latest expat library changes.

rm -f xmlwf.1
test "x" != x && xmlwf.xml
make[8]: [Makefile:605: xmlwf.1] Error 1 (ignored)
test -f xmlwf.1 || mv XMLWF.1 xmlwf.1
mv: cannot stat 'XMLWF.1': No such file or directory
make[8]: [Makefile:606: xmlwf.1] Error 1 (ignored)
Could you please provide your inputs on the above error

**Comment by hartwork** [comment] 2024-10-10 22:31
Hi @anjuvmenon please make this a complete bug report: which tarball exactly (..) on which operating system etc. Make it reproducible and I will try to reproduce. Thank you. PS: Since make is involved, it could be about file modification dates.

**Comment by anjuvmenon** [comment] 2024-10-11 06:19
> Hi @anjuvmenon please make this a complete bug report: which tarball exactly (..) on which operating system etc. Make it reproducible and I will try to reproduce. Thank you. PS: Since make is involved, it could be about file modification dates.

The tarball we are using is expat-2.6.3.tar.gz. Operating system is Linux

**Comment by hartwork** [comment] 2024-10-12 01:39
@anjuvmenon that's good to know but not a reproducer. What I get:

```console
# cd "$(mktemp -d)"
# wget https://github.com/libexpat/libexpat/releases/download/R_2_6_3/expat-2.6.3.tar.gz
# tar xf expat-2.6.3.tar.gz 
# cd expat-2.6.3/
# ./configure
# make -C doc/
make: Entering directory '/tmp/tmp.Pmaoi80W2c/expat-2.6.3/doc'
make: Nothing to be done for 'all'.
make: Leaving directory '/tmp/tmp.Pmaoi80W2c/expat-2.6.3/doc'
```

Please provide a reproducer, a proper bug report. Thank you.

**Comment by hartwork** [comment] 2024-10-12 01:49
PS: Pull request #847 could be related.

**Comment by anjuvmenon** [comment] 2024-10-18 03:30
Can we add --without-docbook in buildconf.sh .

**Comment by hartwork** [comment] 2024-10-18 17:21
@anjuvmenon if you checked the current content of `buildconf.sh` you would know that your suggestion does (1) not solve any problem and (2) does nothing towards my request for a proper bug report. I will close this issue as "supposed AI spam until proven human and proper bug report". I'll also file a report about your user behaving like a bot, next.

**Closed by hartwork** 2024-10-18 17:21 UTC
Labels: question

**Comment by hartwork** [comment] 2024-10-18 17:26
PS: Same as https://github.com/libexpat/libexpat/issues/909#issuecomment-2408293344 with `--without-docbook` added:

```console
# cd "$(mktemp -d)"
# wget https://github.com/libexpat/libexpat/releases/download/R_2_6_3/expat-2.6.3.tar.gz
# tar xf expat-2.6.3.tar.gz 
# cd expat-2.6.3/
# ./configure --without-docbook
# make -C doc/
make: Entering directory '/tmp/tmp.ltqOVkkEAA/expat-2.6.3/doc'
make: Nothing to be done for 'all'.
make: Leaving directory '/tmp/tmp.ltqOVkkEAA/expat-2.6.3/doc'
```
