### ISSUE TITLE
Release archives missing watcomconfig.h

### ISSUE THREAD

**Issue by ArmstrongJ** [libexpat/libexpat#21] opened 2017-04-30 22:22 UTC
I'm trying to build expat's library using the Open Watcom compiler, but the release archives (2.2.0 and 2.1.1 at least) do not appear to contain 'lib/watcomconfig.h', which is being included by a number of files.  The file does seem to exist in the GitHub repo, so I'm not sure how its being left out.

**Comment by hartwork** [comment] 2017-04-30 22:34
Hello Jeff,

I can confirm that `watcomconfig.h` is missing from `expat-2.2.0.tar.bz2`.
While `watcomconfig.h` is present at [`expat/lib/watcomconfig.h`](https://github.com/libexpat/libexpat/blob/HEAD/expat/lib/watcomconfig.h) in Git, it may disappear since we're in the process of [dropping support for Open Watcom](https://github.com/libexpat/libexpat/commit/c808687f32f47396079b62c1c5690646ab7e22ac#diff-d890640aec9ae723533dadce7228b105). If we go forward with dropping Open Watcom support, what kind of trouble do you get into? Please help me understand your Open Watcom scenario.

Thanks and best, Sebastian

**Comment by ArmstrongJ** [comment] 2017-04-30 22:50
I'm building libexpat on Linux using Open Watcom currently.  The compiler package includes a wrapper, `owcc`, that behaves like any normal UNIX-y compiler front end.  The configure script works fine with `CC=owcc`.  

The problem is that mutltiple source files still contain:

```
#elif defined(__WATCOMC__)
#include "watcomconfig.h"
```

If these checks weren't present, I'm guessing Open Watcom would breeze through compiling this library.

**Comment by hartwork** [comment] 2017-04-30 22:56
If you use an empty `watcomconfig.h` or remove these lines, does it compile?

**Comment by ArmstrongJ** [comment] 2017-04-30 23:04
No, it doesn't compile because it won't include `expat_config.h` due to the layout of the preprocessor macros:

```
#ifdef WIN32
#include "winconfig.h"
#elif defined(MACOS_CLASSIC)
#include "macconfig.h"
#elif defined(__amigaos__)
#include "amigaconfig.h"
#elif defined(__WATCOMC__)
#include "watcomconfig.h"
#else
#ifdef HAVE_EXPAT_CONFIG_H
#include <expat_config.h>
#endif
#endif /* ndef WIN32 */
```

**Comment by hartwork** [comment] 2017-04-30 23:07
Do you have `WIN32` defined despite compiling on Linux?

**Comment by ArmstrongJ** [comment] 2017-04-30 23:08
Definitely not.  This situation is Open Watcom compiling on Linux with Linux as the target.  `WIN32` is not defined.

**Comment by hartwork** [comment] 2017-04-30 23:09
Why is `expat_config.h` not pulled in?

**Comment by hartwork** [comment] 2017-04-30 23:17
Could you give [branch `watcom`](https://github.com/libexpat/libexpat/tree/watcom) (with Watcom specific code removed) a try?

**Comment by ArmstrongJ** [comment] 2017-05-01 00:13
That built fine.  FYI I used the following `configure` command:

```
./configure CC=owcc AR=wlib AR_FLAGS=" " RANLIB=echo --enable-static --disable-shared
```

The `#elif defined(__WATCOMC__)` lines were causing the problems.

**Comment by hartwork** [comment] 2017-05-01 11:45
Excellent, merged to `master` now. Thanks for the report and for testing.

**Closed by hartwork** 2017-05-01 11:45 UTC
