### ISSUE TITLE
Compiling expat-2.6.0 for SunOS 5.11/SPARC 64bit

### ISSUE THREAD

**Issue by hicham65** [libexpat/libexpat#846] opened 2024-03-12 14:58 UTC
I have run the following configure command, to compile for 64-bit solaris.

```
CC="cc -m64" CFLAGS="$CFLAGS -fPIC -m64" \
        ./configure --prefix=$expat_tmp_installation_dir  --disable-shared
```

The make went successful, with a 64-bit library 

```
:/tmp/compile/expat-2.6.0$ ls -lt lib/*.o*
-rw-rw-r--   1 hhadjali dba        48256 Mar 12 09:42 lib/xmlrole.o
-rw-rw-r--   1 hhadjali dba       197728 Mar 12 09:42 lib/xmltok.o
-rw-rw-r--   1 hhadjali dba       124656 Mar 12 09:41 lib/xmlparse.o
:/tmp/compile/expat-2.6.0$ file lib/*.o*
lib/xmlparse.o: ELF 64-bit MSB relocatable SPARCV9 Version 1, UltraSPARC3 Extensions Required
lib/xmlrole.o:  ELF 64-bit MSB relocatable SPARCV9 Version 1, UltraSPARC3 Extensions Required
lib/xmltok.o:   ELF 64-bit MSB relocatable SPARCV9 Version 1, UltraSPARC3 Extensions Required
:/tmp/compile/expat-2.6.0$
```

But when I run "gmake check" it failed:

```
FAIL: runtests
============================================================================
Testsuite summary for expat 2.6.0
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/libexpat/libexpat/issues
============================================================================
gmake[4]: *** [Makefile:979: test-suite.log] Error 1
gmake[4]: Leaving directory '/tmp/compile/expat-2.6.0/tests'
gmake[3]: *** [Makefile:1087: check-TESTS] Error 2
gmake[3]: Leaving directory '/tmp/compile/expat-2.6.0/tests'
gmake[2]: *** [Makefile:1192: check-am] Error 2
gmake[2]: Leaving directory '/tmp/compile/expat-2.6.0/tests'
gmake[1]: *** [Makefile:871: check-recursive] Error 1
gmake[1]: Leaving directory '/tmp/compile/expat-2.6.0/tests'
gmake: *** [Makefile:650: check-recursive] Error 1
```

The test-suite.log show the below:

```
:/tmp/compile/expat-2.6.0$ view tests/test-suite.log
=======================================
   expat 2.6.0: tests/test-suite.log
=======================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: runtests
==============

ERROR: check failed: taken > 0
Expat version: expat_2.6.0
FAIL [chunksize=0 deferral=1]: test_big_tokens_take_linear_time (max_slowdown=15 text="<a>aaaaaa</a>" at basic_tests.c:5293)
99%: Checks: 4320, Failed: 1
FAIL runtests (exit status: 1)

```

Any thoughts will be appreciated.

**Comment by hartwork** [comment] 2024-03-12 19:15
Hi @hicham65,

the issue is fixed in release 2.6.**1** by pull request #817. With luck, there will even be 2.6.**2** released tomorrow, so updating to 2.6.2 on say Thursday is likely the best fix.

Best, Sebastian

CC #825 #827 #830 #835

**Closed by hartwork** 2024-03-12 19:15 UTC
