### ISSUE TITLE
expat-win32bin-2.2.9.exe shows 1 virus warning on VirusTotal

### ISSUE THREAD

**Issue by RPORTNOFF** [libexpat/libexpat#376] opened 2020-01-23 17:23 UTC
Is it a false positive? Is this EXE safe to use?

**Comment by hartwork** [comment] 2020-01-23 20:43
There is no definite answer to that question because absense of virus from a compiled result without a fully [reproducable build](https://reproducible-builds.org/) is tricky to prove or even know, right?

What I can say is that:
- We are talking about this entry https://www.virustotal.com/gui/file/a57259ecf093e1f7c0a3a213a54172243ea8b0a3eb85c21fca3c64f1295ef6d6/detection
- The binary with that checksum was built using AppVeyor CI, a direct download from AppVeyor with TLS to me, and a direct upload to GitHub using TLS by me.
- I am not aware of any issues or viruses in that result to this day, I have zero information about the `Malicious.high.ml.score` result by provider `Trapmine` up there.
- I cannot provide any guarantees for AppVeyor's systems. I don't expect them to be infected but it's possible and I don't know.
- The binaries are provided for convenience; for security, I would advise users to compile binaries (of any software not Expat in particular) from sources rather than trusting binaries built by third parties where possible.

Does that answer your question?

**Comment by RPORTNOFF** [comment] 2020-01-23 21:09
Thank you for getting back to me.

When I first checked the file (weeks ago) it was clean. Then yesterday there was 1 listing on VT and now there are 2!

I have scanned my entire machine with Symantec, but that does not show any issues on VT either.

I did scan the unpacked libexpat.dll and libexpat.lib using VT and they show as clean.

Please note that I am using the expat-win32bin-2.2.9.exe instead of plain sources because the LibExpat website reads "Windows users should use the expat_win32 package, which includes both precompiled libraries and executables, and source code for developers."

Anyway, if you can't let me know if this is a valid warning or not, I will have to see if I can find that answer some other way since I have already run the exe. :-/

**Comment by hartwork** [comment] 2020-01-23 21:30
> Thank you for getting back to me.
> 
> When I first checked the file (weeks ago) it was clean. Then yesterday there was 1 listing on VT and now there are 2!

I see! The second engine result — the `SecureAge APEX: Malicious` — appeared only now, after I last visited the page.

> Please note that I am using the expat-win32bin-2.2.9.exe instead of plain sources because the LibExpat website reads "Windows users should use the expat_win32 package, which includes both precompiled libraries and executables, and source code for developers."

That text originates from 94c3265d8a022e1c2f807b4c552611a7141c39bf . (We don't have it on the website on https://libexpat.github.io/ ...) but I agree it's not ideal. I have made it less of a suggestion now in 8a989015ad99f98e221278a5dbeb00f0cee78a5d. (I'm not sure right now if I want to offer use stronger language against binaries there because I'm taking compiling from source further than most people are willing to, e.g. I use Gentoo Linux for a desktop operating system.)

> Anyway, if you can't let me know if this is a valid warning or not, I will have to see if I can find that answer some other way since I have already run the exe. :-/

Please keep this ticket up to date with anything more you might find. Thank you!

**Comment by RPORTNOFF** [comment] 2020-01-23 21:52
It looks like both "SecureAge APEX" and "Trapmine" use "AI" technology instead of relying on signatures of actual known threats, so it's entirely possible that these are both false positives since AI is not an exact science (at least not yet).

So, I am going to wait a few days and see if there are any other engines that report problems with this file on VirusTotal...

**Comment by RPORTNOFF** [comment] 2020-01-25 18:52
I checked VirusTotal again today and the EXE still shows the same 2 warnings.

So I did some tests unrelated to LibExpat. I built some unsigned and signed EXE and DLL files and uploaded them to VirusTotal.

3 of the 4 unsigned files showed the same warnings that I reported for the LibExpat EXE. The SAME files, but signed, all show as CLEAN (no warnings) in VT. Yesterday the 1 file that shows as clean today showed a threat in VT detected by MicroSoft but today shows as clean!

I also signed the expat-win32bin-2.2.9.exe and uploaded it to VT and it too shows as CLEAN!

As you see, the SIGNED version of the SAME files show as CLEAN while the UNSIGNED versions show threats. 

So, why does signing the EXE make it show as clean? Is it because the virus software trusts it and therefore does not scan it (which would be BAD) or is it because signing it changes the EXE in some way that makes it no longer look like a threat?

I have contacted both "SecureAge" and "Trapmine" with that question and I will hopefully hear back from them soon...

The article below says the following:
"The first method to prevent a false positive is to ensure the software is digitally signed. This will allow the antivirus to identify the publisher and hence it won't be marked as a false positive."
https://mspoweruser.com/microsoft-shares-ways-for-software-vendors-to-minimize-false-positives/
I really hope the anti-virus software is not "just trusting" signed files as the bad guys can sign files too!

Interesting article about false positives...
https://weblog.west-wind.com/posts/2016/oct/05/dealing-with-antivirus-false-positives

**Comment by hartwork** [comment] 2020-01-25 18:55
Interesting!

**Comment by hartwork** [comment] 2020-01-25 18:58
I also find it interesting that initial result `Malicious.high.ml.score` by Trapmine now shows as `Malicious.moderate.ml.score` :thinking:

**Comment by RPORTNOFF** [comment] 2020-01-25 19:22
Their "AI" is moody!

**Comment by hartwork** [comment] 2020-01-25 19:48
Or being faked or post-processed by humans...

**Comment by RPORTNOFF** [comment] 2020-01-27 14:41
I sent the EXE to "SecureAge APEX" for review of a possible false positive. "TrapMine" does not seem to offer that upload service so I sent them an email asking if they do.

I did find this article which reads...
https://securelist.com/why-you-shouldnt-completely-trust-files-signed-with-digital-certificates/68593/ 
**"some antivirus scanners automatically consider a file to be secure if it is signed with a valid digital certificate."**
...which is TERRIBLE since this offers a false sense of security!

**Comment by RPORTNOFF** [comment] 2020-01-31 03:09
The "SecureAge APEX" warning is a false positive as per their response below. I never heard back from "Trapmine" regarding sending them the file to analyze. Since that is now the only warning (out of 72), I think it's safe to assume that "Trapmine" is also a false positive.

"Your submission has been successfully processed. Your false detection(s) will be cleared within the next 72 hours; please notify us at secureaplus@secureage.com if that is not the case. For APEX results on VirusTotal, false detections may take additional time to clear. You may need to reanalyse files in order to get the updated detection result."

**Comment by hartwork** [comment] 2020-02-21 20:15
@RPORTNOFF did you receive any replay from Trapmine?

**Comment by RPORTNOFF** [comment] 2020-02-21 20:33
Nope.

**Comment by hartwork** [comment] 2020-02-21 20:45
Okay, thanks for the update!

I'm considering to close this ticket as nothing-more-to-do for now. What do you think?

**Comment by RPORTNOFF** [comment] 2020-02-21 20:49
If they have not responded by now, I doubt they will. I think it's safe to assume that 1 out of 70 is a false-positive so I think you can close this issue.

**Closed** 2020-02-21 21:05 UTC
