### ISSUE TITLE
give option to set XML_SYMBOL_VISIBILITY=0 when building static library with CMake

### ISSUE THREAD

**Issue by mardigontoler** [libexpat/libexpat#626] opened 2022-08-12 19:37 UTC
Currently, when `-fvisibility` is set to `hidden` in the CMake script, `XML_ENABLE_VISIBILITY` is always defined as 1 so that the expat API is annotated with `__attribute__((visibility("default")))`. 

However, when building expat as a static library that will be linked into a shared library, it can be helpful to make those functions hidden as well so that they're not exposed by the host shared library.

Would it make sense to alter CMakeLists.txt so that when visibility is configured, `XML_ENABLE_VISIBILITY` is set to 0 if `EXPAT_SHARED_LIBS` is false? Alternatively, could we add another option to control this?

I would be happy to create a pull request based on feedback.

EDIT: Grammar.

**Comment by hartwork** [comment] 2022-08-12 22:46
Hi @mardigontoler ,

I believe there may be a misunderstanding here, let's find out! My impression is that — as of the latest release 2.4.8 and also on Git `master` — when the compiler is found to support visibility compile time options, two things happen for both static and shared library builds: (1) the default visibility is set hidden while (2) all symbols that are considered are explicitly marked as not-to-hide. So if you are using recent Expat and want symbols to be hidden for a static library build, I would expect that to already happen. Please help me understand where status quo does not match your expected result. Thank you! :beers:

**Comment by mardigontoler** [comment] 2022-08-14 04:54
Thank you for reaching out so soon.  Your description matches my understanding so far. 

I am building a static expat library from the 2.4.8 tag like this:
```bash
cmake .. -G "Xcode" -DEXPAT_SHARED_LIBS=OFF
cmake --build . --target expat --config Debug
```

As you said, the functions that make up the public API are being explicitly marked not-to-hide, using `__attribute__((visibility("default")))`, because the CMake script sets `XML_ENABLE_VISIBILITY=1`, which determines the XMLIMPORT macro in `expat_external.h`. If I inspect the built static library with `nm libexpat.a | grep "T "`, I can see them all. 

The issue is that when I create my own dynamic library that links to expat statically, these globally exported symbols are then leaked into my own library's exported symbols. Then, if my dynamic library loads _other_ dynamic libraries that statically linked against different versions of expat themselves, then there can be a symbol collision in the global namespace, as described [this article by Benjamin Supnik](http://hacksoflife.blogspot.com/2012/12/static-libraries-and-plugins-global-pain.html). 

When I link the static expat library into my dynamic library, I see the symbols that were explicitly marked with default visibility:
```bash
$ nm libMyLib.dylib | grep " T"

0000000000008500 T _XML_DefaultCurrent
0000000000008700 T _XML_ErrorString
0000000000008ab0 T _XML_ExpatVersion
0000000000008ac0 T _XML_ExpatVersionInfo
0000000000004dc0 T _XML_ExternalEntityParserCreate
00000000000083f0 T _XML_FreeContentModel
00000000000068a0 T _XML_GetBase
00000000000073d0 T _XML_GetBuffer
0000000000008130 T _XML_GetCurrentByteCount
00000000000080c0 T _XML_GetCurrentByteIndex
0000000000008330 T _XML_GetCurrentColumnNumber
0000000000008260 T _XML_GetCurrentLineNumber
0000000000008080 T _XML_GetErrorCode
0000000000008af0 T _XML_GetFeatureList
0000000000006920 T _XML_GetIdAttributeIndex
00000000000081a0 T _XML_GetInputContext
0000000000008000 T _XML_GetParsingStatus
00000000000068e0 T _XML_GetSpecifiedAttributeCount
00000000000084d0 T _XML_MemFree
0000000000008430 T _XML_MemMalloc
0000000000008480 T _XML_MemRealloc
0000000000007050 T _XML_Parse
0000000000007a80 T _XML_ParseBuffer
0000000000003e10 T _XML_ParserCreate
0000000000003e70 T _XML_ParserCreateNS
0000000000003e40 T _XML_ParserCreate_MM
0000000000005fa0 T _XML_ParserFree
00000000000042d0 T _XML_ParserReset
0000000000007e50 T _XML_ResumeParser
0000000000006ea0 T _XML_SetAttlistDeclHandler
0000000000006730 T _XML_SetBase
0000000000008c00 T _XML_SetBillionLaughsAttackProtectionActivationThreshold
0000000000008b00 T _XML_SetBillionLaughsAttackProtectionMaximumAmplification
0000000000006a90 T _XML_SetCdataSectionHandler
0000000000006a00 T _XML_SetCharacterDataHandler
0000000000006a60 T _XML_SetCommentHandler
0000000000006b30 T _XML_SetDefaultHandler
0000000000006b70 T _XML_SetDefaultHandlerExpand
0000000000006bb0 T _XML_SetDoctypeDeclHandler
0000000000006e70 T _XML_SetElementDeclHandler
0000000000006960 T _XML_SetElementHandler
0000000000004c30 T _XML_SetEncoding
0000000000006b00 T _XML_SetEndCdataSectionHandler
0000000000006c20 T _XML_SetEndDoctypeDeclHandler
00000000000069d0 T _XML_SetEndElementHandler
0000000000006d20 T _XML_SetEndNamespaceDeclHandler
0000000000006ed0 T _XML_SetEntityDeclHandler
0000000000006d80 T _XML_SetExternalEntityRefHandler
0000000000006db0 T _XML_SetExternalEntityRefHandlerArg
0000000000006fa0 T _XML_SetHashSalt
0000000000006cb0 T _XML_SetNamespaceDeclHandler
0000000000006d50 T _XML_SetNotStandaloneHandler
0000000000006c80 T _XML_SetNotationDeclHandler
0000000000006f30 T _XML_SetParamEntityParsing
0000000000006a30 T _XML_SetProcessingInstructionHandler
0000000000006670 T _XML_SetReturnNSTriplet
0000000000006e00 T _XML_SetSkippedEntityHandler
0000000000006ad0 T _XML_SetStartCdataSectionHandler
0000000000006bf0 T _XML_SetStartDoctypeDeclHandler
00000000000069a0 T _XML_SetStartElementHandler
0000000000006cf0 T _XML_SetStartNamespaceDeclHandler
0000000000006e30 T _XML_SetUnknownEncodingHandler
0000000000006c50 T _XML_SetUnparsedEntityDeclHandler
00000000000066d0 T _XML_SetUserData
0000000000006f00 T _XML_SetXmlDeclHandler
0000000000007d40 T _XML_StopParser
0000000000006600 T _XML_UseForeignDTD
00000000000065d0 T _XML_UseParserAsHandlerArg
0000000000003b80 T __Z17mylib_dosomethingv
```

Since these symbols are being exported by _my own_ library, then if it loads any other libraries that are themselves linked against a static expat library, then that library's expat calls could end up calling into _my_ library's expat code.

I've been able to avoid this situation by changing [this section of expat's CMakeLists.txt](https://github.com/libexpat/libexpat/blob/R_2_4_8/expat/CMakeLists.txt#L291) to this:
```CMake
if(FLAG_VISIBILITY)
  if(EXPAT_SHARED_LIBS)
    add_definitions(-DXML_ENABLE_VISIBILITY=1)
  else()
    add_definitions(-DXML_ENABLE_VISIBILITY=0)  # prevent leaking symbols when statically linking to expat
  endif()
  set(EXTRA_COMPILE_FLAGS "${EXTRA_COMPILE_FLAGS} -fvisibility=hidden")
endif()
```

**Comment by hartwork** [comment] 2022-08-14 17:39
@mardigontoler is this something specific to macOS? I have been experimenting with this on my local Linux box now and I cannot see any Expat symbols "leaking" into a shared library linking against static Expat, even with the current code on `master`.

**Comment by mardigontoler** [comment] 2022-08-15 15:51
I just gave it a try on Linux with g++ 9.4.

```bash
$ cd libexpat/expat
$ mkdir build
$ rm -rf *
$ cmake .. -DEXPAT_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
$ cmake --build . --target expat
```

Then, I created this test project in a sibling directory to my clone of this repository:
```bash
$ cd expatDemo
$ cat mylib.cpp 
#include <expat.h>
#include <iostream>

static void XMLCALL
startElement(void *userData, const XML_Char *name, const XML_Char**atts)
{
    return;
}

static void XMLCALL
endElement(void *userData, const XML_Char *name)
{
    return;
}

int doSomething()
{
    XML_Parser parser = XML_ParserCreate(NULL);
    char buf[90000];
    int done;
    int depth = 0;
    XML_SetUserData(parser, &depth);
    XML_SetElementHandler(parser, startElement, endElement);
    XML_ParserFree(parser);
    return 0;
}
```

```bash
$ cat CMakeLists.txt 
cmake_minimum_required(VERSION 3.9)

project(expat_example)

add_library(my_lib SHARED mylib.cpp)

set(CMAKE_CXXVISIBILITY_PRESET hidden)
set(CMAKE_C_VISIBILITY_PRESET hidden)
set(CMAKE_VISIBILITY_INLINES_HIDDEN ON)

target_include_directories(my_lib PRIVATE ${CMAKE_CURENT_SOURCE_DIR}/../libexpat/expat/lib)
target_link_libraries(my_lib ${CMAKE_CURRENT_SOURCE_DIR}/../libexpat/expat/build/libexpat.a)

```

```bash
$ mkdir build
$ cd build
$ rm -rf * && cmake .. && cmake -build .
```

Then, `nm -D  libmy_lib.so | grep "T "` shows the same output that I posted in my comment above, so it seems that statically linking against libexpat.a has caused those symbols to be exported in the dynmaic symbol table of libmy_lib.so.

**Comment by hartwork** [comment] 2022-09-12 14:48
@mardigontoler sorry it took me so long to have a closer look! Thanks for providing the reproducer above! :+1:

After adding `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fvisibility=hidden")`
I was able to see the effect you describe.

(Without that addition it wouldn't work because `CMAKE_CXXVISIBILITY_PRESET` had a typo and even after correcting it to `CMAKE_CXX_VISIBILITY_PRESET` and adding `VERBOSE=1` to the build nothing would would pass `-fvisibility=hidden` to the compiler in practice (with CMake 3.24.1 and GCC 11.3.0) over here.)

Given what `lib/expat_external.h` currently does with undefined `XML_ENABLE_VISIBILITY`…

```console
# git --no-pager grep XML_ENABLE_VISIBILITY -- lib
lib/expat_external.h:#ifndef XML_ENABLE_VISIBILITY
lib/expat_external.h:#  define XML_ENABLE_VISIBILITY 0
lib/expat_external.h:#if ! defined(XMLIMPORT) && XML_ENABLE_VISIBILITY
```

…I believe this could be a helpful, clean, minimal pull request:

```diff
---     add_definitions(-DXML_ENABLE_VISIBILITY=1)
+++   if(EXPAT_SHARED_LIBS)
+++     add_definitions(-DXML_ENABLE_VISIBILITY=1)
+++   endif()
```

What do you think?

PS: The first shell block in your latest post is missing `cd build` so the `rm -rf *` would effectively delete all of Expat and the new empty `build` folder when executed as copied. (On a general note, I advise to never call `rm -rf *` verbatim anywhere (e.g. to not have that command go into shell history and then come back in <kbd>Ctrl+R</kbd> search matches) but rather do something like `rm -rf build/*` or `rm -rf build/` with much lower universal damage potential, instead.)

Best, Sebastian

**Comment by hartwork** [comment] 2022-09-12 15:21
@mardigontoler I have taken care of the GNU Autotools side of things as well now and packaged both up as pull request #641. Would be great if you could check it out. Thanks! :pray:

**Comment by mardigontoler** [comment] 2022-09-12 15:37
Thanks for looking into this @hartwork. Your proposed CMake change is what I have been doing in the meantime to resolve this for myself, so all looks good there. The Autotools changes also make sense to me.

That pull requests seems good to me. 👍

**Comment by hartwork** [comment] 2022-09-12 15:44
@mardigontoler excellent, thanks for the review and the extra fast response! :+1: :+1:
If the PR passes CI, I'll merge and close the issue as fixed.

**Closed** 2022-09-12 16:19 UTC
Labels: enhancement, compilation
