### ISSUE TITLE
Please provide prebuilt binaries for Win64

### ISSUE THREAD

**Issue by tqo50396** [libexpat/libexpat#791] opened 2023-11-25 20:33 UTC
I downloaded [expat-win32bin-2.5.0.zip](https://github.com/libexpat/libexpat/releases/download/R_2_5_0/expat-win32bin-2.5.0.zip) and I found that it's 32 bit.

**Comment by hartwork** [comment] 2023-11-25 20:39
@tqo50396 I encourage everyone to build their own binaries even if it's maybe not common on Windows yet. I keep producing 32bit binaries only because there have been some before my time and it feels wrong to take them away and the integration to do that is ready, and have no access to Windows outside of CI. 64bit Windows binaries will need some form of help or a sponsor to happen. Thanks for your understanding.

**Comment by hartwork** [comment] 2023-11-25 20:45
Closing as a duplicate of #139 and #203 and pinning this issue. Happy to re-open if you do want to help/sponsor this feature.

**Closed by hartwork** 2023-11-25 20:45 UTC
Labels: wontfix, windows

**Comment by hartwork** [comment] 2025-01-21 01:48
A quick update for anyone interested in 64bit Expat Windows binaries:

[Expat 2.6.4](https://github.com/libexpat/libexpat/releases/tag/R_2_6_4) is the first release to come with 64bit Windows binaries. These binaries were built by GitHub Actions at https://github.com/libexpat/libexpat/actions/runs/12878310769 based on the work from pull request #946. If you find any issues with these new 64bit binaries specifically, please [report that as a new issue](https://github.com/libexpat/libexpat/issues) and we'll see about a fix for Expat >=2.6.5, together. Thank you!
