### ISSUE TITLE
XML_Parse() returns XML_ERROR_JUNK_AFTER_DOC_ELEMENT when input XML size exceeds 4 KB

### ISSUE THREAD

**Issue by pruthig** [libexpat/libexpat#256] opened 2019-04-25 12:06 UTC
I am loading an XML file into a buffer. XML parsing is successful when file size is <=4096 bytes. But I get an error - XML_ERROR_JUNK_AFTER_DOC_ELEMENT  when file size exceeds 4096 bytes. Is there some restrictions inside the library regarding the size?

P.S - To increase the size, I just add text to comments

**Comment by RMJ10** [comment] 2019-04-26 13:09
Could you give an example of an XML file that fails, please?  I can't test this right at the moment, but I suspect you have something like:

    <doc>
      Some useful XML I want to parse
    </doc>
    

and expat is complaining that you have stuff after the document element.  It should accept comments, though.  I'll test this when I get home.

**Comment by hartwork** [comment] 2019-04-27 19:24
Hi!

There is no 4K limit and comments after root nodes are well-formed XML and supported to mye best knowledge. My guess is that you have a document with multiple root nodes — which is not well-formed XML — like this:

```console
# cat foo.xml
<?xml version="1.0" encoding="UTF-8"?>
<root/>
<!-- comment after document -->
<invalid/>

# ./examples/outline < foo.xml
root
Parse error at line 4:
junk after document element
```

**Comment by hartwork** [comment] 2019-05-12 17:46
@pruthig closing this ticket as "not a bug". If you come to know some else later, please comment to this ticket, we can re-open the bug any time. Thanks!

**Closed by hartwork** 2019-05-12 17:46 UTC
Labels: invalid, question
