### ISSUE TITLE
Link error "Undefined symbol: ._isnanf" on AIX

### ISSUE THREAD

**Issue by sunilramapur** [libexpat/libexpat#509] opened 2021-09-07 12:48 UTC
```
        make  all-recursive
Making all in lib
        /bin/sh ../libtool  --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I. -I..  -DXML_ENABLE_VISIBILITY=1   -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmlparse.lo -MD -MP -MF .deps/xmlparse.Tpo -c -o xmlparse.lo xmlparse.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DXML_ENABLE_VISIBILITY=1 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmlparse.lo -MD -MP -MF .deps/xmlparse.Tpo -c xmlparse.c  -fPIC -DPIC -o .libs/xmlparse.o
xmlparse.c: In function 'accountingReportDiff':
**xmlparse.c:7278:11: warning: format '%d' expects argument of type 'int', but argument 3 has type 'ptrdiff_t' {aka 'long int'} [-Wformat=]
           " (+" EXPAT_FMT_PTRDIFF_T("6") " bytes %s|%d, xmlparse.c:%d) %*s\"",
           ^~~~~
           bytesMore, (account == XML_ACCOUNT_DIRECT) ? "DIR" : "EXP",
           ~~~~~~~~~
In file included from xmlparse.c:195:
internal.h:127:55: note: format string is defined here
 #    define EXPAT_FMT_PTRDIFF_T(midpart) "%" midpart "d"
                                           ~~~~~~~~~~~~^
                                           %" midpart "ld
xmlparse.c: At top level:
cc1: warning: unrecognized command line option '-Wno-pedantic-ms-format'**
        mv -f .deps/xmlparse.Tpo .deps/xmlparse.Plo
        /bin/sh ../libtool  --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I. -I..  -DXML_ENABLE_VISIBILITY=1   -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmltok.lo -MD -MP -MF .deps/xmltok.Tpo -c -o xmltok.lo xmltok.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DXML_ENABLE_VISIBILITY=1 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmltok.lo -MD -MP -MF .deps/xmltok.Tpo -c xmltok.c  -fPIC -DPIC -o .libs/xmltok.o
        mv -f .deps/xmltok.Tpo .deps/xmltok.Plo
        /bin/sh ../libtool  --tag=CC    --mode=compile gcc -DHAVE_CONFIG_H  -I. -I..  -DXML_ENABLE_VISIBILITY=1   -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmlrole.lo -MD -MP -MF .deps/xmlrole.Tpo -c -o xmlrole.lo xmlrole.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -DXML_ENABLE_VISIBILITY=1 -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2 -MT xmlrole.lo -MD -MP -MF .deps/xmlrole.Tpo -c xmlrole.c  -fPIC -DPIC -o .libs/xmlrole.o
        mv -f .deps/xmlrole.Tpo .deps/xmlrole.Plo
        /bin/sh ../libtool  --tag=CC    --mode=link gcc -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2  -fno-strict-aliasing  -o libexpatinternal.la  xmlparse.lo xmltok.lo xmlrole.lo
libtool: link: ar cru .libs/libexpatinternal.a .libs/xmlparse.o .libs/xmltok.o .libs/xmlrole.o
libtool: link: ranlib .libs/libexpatinternal.a
libtool: link: ( cd ".libs" && rm -f "libexpatinternal.la" && ln -s "../libexpatinternal.la" "libexpatinternal.la" )
        /bin/sh ../libtool  --tag=CC    --mode=link gcc -Wall -Wextra -fexceptions -fno-strict-aliasing -Wmissing-prototypes -Wstrict-prototypes -pedantic -Wduplicated-cond -Wduplicated-branches -Wlogical-op -Wrestrict -Wnull-dereference -Wjump-misses-init -Wdouble-promotion -Wshadow -Wformat=2 -Wno-pedantic-ms-format -Wmisleading-indentation -fvisibility=hidden -g -O2  -fno-strict-aliasing  -no-undefined  -version-info 9:0:8  -o libexpat.la -rpath /app/tomcat/apache_webserver/APR/lib  libexpatinternal.la
libtool: link: `func_echo_all /usr/bin/nm -B | /opt/freeware/bin/sed -e 's/B\([^B]*\)$/P\1/'` -PCpgl   ./.libs/libexpatinternal.a | awk '{ if ((($ 2 == "T") || ($ 2 == "D") || ($ 2 == "B") || ($ 2 == "W") || ($ 2 == "V") || ($ 2 == "Z")) && (substr($ 1,1,1) != ".")) { if (($ 2 == "W") || ($ 2 == "V") || ($ 2 == "Z")) { print $ 1 " weak" } else { print $ 1 } } }' | sort -u > .libs/libexpat.exp
libtool: link: rm -f -r .libs/libexpat.a.d
libtool: link: mkdir .libs/libexpat.a.d
libtool: link: gcc -shared -o .libs/libexpat.a.d/libexpat.so.1   ./.libs/libexpatinternal.a  -lc -Wl,-bnoentry `func_echo_all " -g -O2   " | /opt/freeware/bin/sed -e "s%-brtl\\([, ]\\)%-berok\\1%g"`-Wl,-bE:.libs/libexpat.exp -Wl,-bernotok
ld: 0711-317 ERROR: Undefined symbol: ._isnanf
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
collect2: error: ld returned 8 exit status
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 1.


Stop.
make: 1254-004 The error code from the last command is 2.


Stop.
```

**Comment by hartwork** [comment] 2021-09-07 13:06
@sunilramapur please make this a proper bug report. What compiler are you using, what operating system, what libc library, what hardware etc. Is this about an embedded device without a floating point unit?

**Comment by sunilramapur** [comment] 2021-09-08 03:55
Hi,
Apologies for posting just the error from make command. Below are details which could help to assist us.

1. OS - AIX 7.2
2. Compiler - GCC 8.3
3. Linker - GCC Linker (/usr/bin/ld)
4. Hardware details :
System Model: IBM,9080-M9S
Machine Serial Number: Not Available
Processor Type: PowerPC_POWER9
Processor Implementation Mode: POWER 9
Processor Version: PV_9_Compat
Number Of Processors: 2
Processor Clock Speed: 3000 MHz
CPU Type: 64-bit
Kernel Type: 64-bit
Memory Size: 32768 MB
Good Memory Size: 32768 MB
Platform Firmware level: VH940_074
Firmware Version: IBM,FW940.31 (VH940_074)
NX Crypto Acceleration: Capable and Enabled
In-Core Crypto Acceleration: Capable, but not Enabled

5. EXPAT - configure command outpu.txt (https://github.com/libexpat/libexpat/files/7125698/EXPAT.-.configure.command.outpu.txt)

I couldn't find what libc library is used. It would be good if someone can guide me how to identify it.

**Comment by hartwork** [comment] 2021-09-08 14:45
@sunilramapur thanks for these details. From my current understanding:
- You're on a compiler and platform that is supported and can be expected to build and work out of the box. This seems to be an actual build system bug.
- The use of function `isnan` seems to require linking against libm (`-lm`) but Expat is doing that in the build system but should.
- The warning about `long int` above seems to indicate that 64bit detection (for format strings) may not be working as expected on AIX.

What I'd like to do is two things:
- Create a pull request for linking against libm where needed and then ask you to compile that pull request on AIX using both build systems — Autotools and CMake — so we have both sides covered. (Can I assume you have CMake >=3.1.3 available on AIX?)
- Write and share a tiny C program to adi debugging of the code at https://github.com/libexpat/libexpat/blob/9f742632bae28dea97d6c4b77038608e932d05eb/expat/lib/internal.h#L110-L130 on AIX, because something in there does not seem to work well for AIX at the moment.

So I have work to do here now. If you have any questions or comments before I come back with code, please go ahead.

**Comment by hartwork** [comment] 2021-09-08 15:12
@sunilramapur to understanding the 64bit detection problem better, I'd like to ask you to compile and run the C code below on AIX. Here's the invocation and output for my local x86_64 Linux machine:

```console
# gcc -Wall -Wextra warn509.c && ./a.out
2 non-windows
2.2 non-windows, 64bit
EXPAT_FMT_PTRDIFF_T("6") is "%6ld"
EXPAT_FMT_SIZE_T("6") is "%6lu"
ULONG_MAX is 18446744073709551615
sizeof(int) is 4
sizeof(long int) is 8
```
The code in file `warn509.c` is this:
```C
#include <stdio.h>
#include <limits.h> // ULONG_MAX

int main() {

#if defined(_WIN32) && ! defined(__USE_MINGW_ANSI_STDIO) 
    printf("1 windows\n");
#  define EXPAT_FMT_ULL(midpart) "%" midpart "I64u" 
#  if defined(_WIN64) // Note: modifiers "td" and "zu" do not work for MinGW 
    printf("1.1 windows, 64bit\n");
#    define EXPAT_FMT_PTRDIFF_T(midpart) "%" midpart "I64d" 
#    define EXPAT_FMT_SIZE_T(midpart) "%" midpart "I64u" 
#  else 
    printf("1.2 windows, 32bit\n");
#    define EXPAT_FMT_PTRDIFF_T(midpart) "%" midpart "d" 
#    define EXPAT_FMT_SIZE_T(midpart) "%" midpart "u" 
#  endif 
#else 
    printf("2 non-windows\n");
#  define EXPAT_FMT_ULL(midpart) "%" midpart "llu" 
#  if ! defined(ULONG_MAX) 
#    error Compiler did not define ULONG_MAX for us 
#  elif ULONG_MAX == 18446744073709551615u // 2^64-1 
    printf("2.2 non-windows, 64bit\n");
#    define EXPAT_FMT_PTRDIFF_T(midpart) "%" midpart "ld" 
#    define EXPAT_FMT_SIZE_T(midpart) "%" midpart "lu" 
#  else 
    printf("2.3 non-windows, 32bit\n");
#    define EXPAT_FMT_PTRDIFF_T(midpart) "%" midpart "d" 
#    define EXPAT_FMT_SIZE_T(midpart) "%" midpart "u" 
#  endif 
#endif

    printf("EXPAT_FMT_PTRDIFF_T(\"6\") is \"%s\"\n", EXPAT_FMT_PTRDIFF_T("6"));
    printf("EXPAT_FMT_SIZE_T(\"6\") is \"%s\"\n", EXPAT_FMT_SIZE_T("6"));
    printf("ULONG_MAX is %lu\n", ULONG_MAX);
    printf("sizeof(int) is %d\n", (int)sizeof(int));
    printf("sizeof(long int) is %d\n", (int)sizeof(long int));

    return 0;
}
```

Would be great if you could share your results on that code. Thanks in advance!

**Comment by hartwork** [comment] 2021-09-08 16:42
@sunilramapur for the link error, there is pull request #510 now. The description of the pull request contains instructions how to build the related Git branch for each build system, easily. Thanks in advance!

**Comment by sunilramapur** [comment] 2021-09-09 04:29
Hi Sebastian,
Thanks a lot for picking up the request and lending your helping hand.
Here is the output of the C code from my AIX machine.

$ gcc -Wall -Wextra warn509.c && ./a.out
2 non-windows
2.3 non-windows, 32bit
EXPAT_FMT_PTRDIFF_T("6") is "%6d"
EXPAT_FMT_SIZE_T("6") is "%6u"
ULONG_MAX is 4294967295
sizeof(int) is 4
sizeof(long int) is 4

**Comment by hartwork** [comment] 2021-09-09 11:56
@sunilramapur thanks for your reply. I am quite surprised that `long int` is only 32bit on your 64bit AIX box. Then yes, Expat's current 64bit detection does not work for AIX, at least not for yours. Is there anything that you did to force that setting, are you forcing 32bit mode somewhere? Is that common on 64bit AIX? Does your kernel support 64bit?

Can we do the same game again with the new C code below?:
```console
# gcc -Wall -Wextra ppc64.c && ./a.out
Defined:
  __powerpc64__       : No
  __ppc64__           : No
  __PPC64__           : No
  _ARCH_PPC64         : No

Sizes:
  long                : 8
  long long           : 8
  unsigned long       : 8
  unsigned long long  : 8
```

For file `ppc64.c` I have:
```c
#include <stdio.h>

int main() {
    printf("Defined:\n");

#ifdef __powerpc64__
    printf("  __powerpc64__       : Yes\n");
#else
    printf("  __powerpc64__       : No\n");
#endif

#ifdef __ppc64__
    printf("  __ppc64__           : Yes\n");
#else
    printf("  __ppc64__           : No\n");
#endif

#ifdef __PPC64__
    printf("  __PPC64__           : Yes\n");
#else
    printf("  __PPC64__           : No\n");
#endif

#ifdef _ARCH_PPC64
    printf("  _ARCH_PPC64         : Yes\n");
#else
    printf("  _ARCH_PPC64         : No\n");
#endif
    
    printf("\nSizes:\n");
    printf("  long                : %d\n", (int)sizeof(long));
    printf("  long long           : %d\n", (int)sizeof(long long));
    printf("  unsigned long       : %d\n", (int)sizeof(unsigned long));
    printf("  unsigned long long  : %d\n", (int)sizeof(unsigned long long));

    return 0;
}
```

Looking forward to your results for pull request #510 as well.

**Comment by hartwork** [comment] 2021-09-09 12:04
@mperzl if you have a minute, I'd be happy about your AIX glasses on this

**Comment by sunilramapur** [comment] 2021-09-09 16:37
Hi Sebastian,
Here is output of C program on my AIX machine.

$ gcc -Wall -Wextra ppc64.c && ./a.out
Defined:
  __powerpc64__       : No
  __ppc64__           : No
  __PPC64__           : No
  _ARCH_PPC64         : No

Sizes:
  long                : 4
  long long           : 8
  unsigned long       : 4
  unsigned long long  : 8

Let me check and get back to you regarding the 32 bit mode on my AIX.
I am encountering error while running the commands mentioned in pull request #510. Not sure whether it permission issue.

$git clone --branch issue-509-link-against-libm --depth 1 https://github.com/libexpat/libexpat
Cloning into 'libexpat'...
fatal: unable to access 'https://github.com/libexpat/libexpat/': Could not resolve host: github.com

**Comment by hartwork** [comment] 2021-09-09 16:58
@sunilramapur thanks for testing and your reply.

> Here is output of C program on my AIX machine.
> ```console
> $ gcc -Wall -Wextra ppc64.c && ./a.out
> Defined:
>   __powerpc64__       : No
>   __ppc64__           : No
>   __PPC64__           : No
>   _ARCH_PPC64         : No
> [..]
> ```

That is unfortunate: We cannot use any of these macros to detect 64bit AIX then.

> Let me check and get back to you regarding the 32 bit mode on my AIX.

Cool, thanks in advance.

> I am encountering error while running the commands mentioned in pull request #510. Not sure whether it permission issue.
> ```console
> $ git clone --branch issue-509-link-against-libm --depth 1 https://github.com/libexpat/libexpat
> Cloning into 'libexpat'...
> fatal: unable to access 'https://github.com/libexpat/libexpat/': Could not resolve host: github.com
> ```

That seems like a DNS or general connectivity problem. Maybe a corporate firewall is at work. Unless the issue is temporary, this will likely need a fix in your environment.

**Comment by hartwork** [comment] 2021-09-11 20:58
@sunilramapur according to https://www.ibm.com/docs/en/aix/7.2?topic=s-sysconf-subroutine there are four different C-language compilation environments on AIX:

> `_SC_XBS5_ILP32_OFF32` — Implementation provides a C-language compilation environment with 32-bit int, long, pointer and off_t types.
> `_SC_XBS5_ILP32_OFFBIG` — Implementation provides a C-language compilation environment with 32-bit int, long and pointer types and an off_t type using at least 64 bits.
> `_SC_XBS5_LP64_OFF64` — Implementation provides a C-language compilation environment with 32-bit int and 64-bit long, pointer and off_t types.
> `_SC_XBS5_LPBIG_OFFBIG` — Implementation provides a C-language compilation environment with an int type using at least 32 bits and long, pointer and off_t types using at least 64 bits.

The two `*_OFFBIG` variants would explain the behavior of your box.

Let's focus on pull request #510 and the link error first, though. If we can get that out the door fully by the end of week 37 together, that would be awesome.

**Comment by hartwork** [comment] 2021-09-14 16:38
@sunilramapur any news?

**Comment by hartwork** [comment] 2021-09-20 16:50
@sunilramapur I got my hands on one the AIX machines of [GCC Comile Farm](https://cfarm.tetaneutral.net/machines/list/) now. On AIX 7.1 `gcc111.fsffrance.org`, prior to calling `./buildconf.sh` I had to:
- (Apply `export ACLOCAL_PATH="$(which libtool)/../../share/aclocal${ACLOCAL_PATH:+:}${ACLOCAL_PATH}"` due to non-standard location of libtool, to make aclocal find libtool m4 files)
- (Apply `export M4="$(which m4)"` prior to calling `./buildconf.sh` due to non-standard location of recent enough m4)
- Call `libtoolize` (so that autoreconf no longer fails to detect use of libtool; seems like a bug somewhere)
- Put a selfmade `mktemp` command into `${PATH}` (because that command seems missing on AIX)

Then, _before_ patching away link errors, I get the same `Undefined symbol: ._isnanf`. With pull request #510 applied, those link errors go away with GNU Autotools; however CMake still fails with:
```
ld: 0711-317 ERROR: Undefined symbol: _GLOBAL__AIXI_libexpat_so
ld: 0711-317 ERROR: Undefined symbol: _GLOBAL__AIXD_libexpat_so
ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information.
```

I am not sure what's causing this issue. **I will likely rely on pull requests from you or the AIX community to fix this seemingly AIX specific issue, both the CMake one and the `printf` format string related (seemingly harmless) warning.** Contributions in that direction will be welcome. For now, I will close this issue here (#509) after merging pull request #510 because the Autotools build system link error — the heart of this ticket — is fixed and due to the recent 12 days of silence. Please be encouraged to open new tickets and/or reply here as you see fit. Thank you. :pray:

**Closed** 2021-09-20 17:19 UTC
Labels: bug, compilation
